import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, CircleAlert, FileSearch, LayoutDashboard, Megaphone, Radio, Shapes } from "lucide-react";
import { Link, NavLink, Outlet, useParams, useSearchParams } from "react-router-dom";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, LabelList, XAxis, YAxis } from "recharts";
import type { ReactNode } from "react";
import { uk } from "date-fns/locale";
import type { DateRange as PickerRange } from "react-day-picker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { apiClient, type Daily, type DateRange, type Entity, type Evidence, type Page, type RhetoricAggregate, type RhetoricLabel, type Stance, type Summary } from "./api/client";

const size = 25;
const colors: Record<Stance, string> = { позитивне: "bg-emerald-500/10 text-emerald-700", негативне: "bg-rose-500/10 text-rose-700", відсутнє: "bg-muted text-muted-foreground" };
const types: Record<string, string> = { person: "Людина", organization: "Організація", state_institution: "Державна установа", media: "Медіа" };
const rhetoricLabels: Record<RhetoricLabel, string> = { корупція_або_особиста_вигода: "Корупція / особиста вигода", злочинна_або_незаконна_поведінка: "Злочинна / незаконна поведінка", делегітимізація: "Делегітимізація", лицемірство_або_подвійні_стандарти: "Лицемірство / подвійні стандарти", висміювання_або_особиста_образа: "Висміювання / особиста образа", зовнішній_контроль_або_нелояльність: "Зовнішній контроль / нелояльність" };
const number = (x: number | undefined) => Number(x ?? 0).toLocaleString("uk-UA");
const labelDate = (x: string) => new Intl.DateTimeFormat("uk-UA", { day: "2-digit", month: "short" }).format(new Date(x));
const isoStart = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).toISOString();
const isoEnd = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1).toISOString();
const initial = (() => { const end = new Date(); const start = new Date(end); start.setDate(end.getDate() - 30); return { start: isoStart(start), end: isoEnd(end) }; })();
const dates = (p: URLSearchParams) => p.get("period") === "all" ? {} : { start: p.get("start") ?? initial.start, end: p.get("end") ?? initial.end };

function DateRange() {
  const [p, setP] = useSearchParams(); const value = dates(p);
  const selected = value.start && value.end ? { from: new Date(value.start), to: new Date(new Date(value.end).getTime() - 86400000) } : undefined;
  const apply = (from?: Date, to?: Date) => { if (!from || !to) return; p.set("start", isoStart(from)); p.set("end", isoEnd(to)); p.delete("period"); p.delete("offset"); p.delete("channel_offset"); p.delete("evidence_offset"); p.delete("claim_offset"); setP(p); };
  const preset = (days?: number) => { if (!days) { p.delete("start"); p.delete("end"); p.set("period", "all"); p.delete("offset"); p.delete("channel_offset"); p.delete("evidence_offset"); p.delete("claim_offset"); setP(p); return; } const to = new Date(); const from = new Date(to); from.setDate(to.getDate() - days + 1); apply(from, to); };
  const text = p.get("period") === "all" ? "Увесь час" : value.start && value.end ? labelDate(value.start) + " — " + labelDate(new Date(new Date(value.end).getTime() - 86400000).toISOString()) : "Останні 30 днів";
  return <Popover><PopoverTrigger className="inline-flex h-9 items-center rounded-md border px-3 text-sm hover:bg-accent"><CalendarDays className="mr-2 size-4" />{text}</PopoverTrigger><PopoverContent className="w-auto p-3" align="end"><div className="mb-2 flex gap-1"><Button size="sm" variant="ghost" onClick={() => preset(7)}>7 днів</Button><Button size="sm" variant="ghost" onClick={() => preset(30)}>30 днів</Button><Button size="sm" variant="ghost" onClick={() => preset(90)}>90 днів</Button><Button size="sm" variant="ghost" onClick={() => preset()}>Увесь час</Button></div><Calendar mode="range" selected={selected as PickerRange} onSelect={(v) => apply(v?.from, v?.to)} locale={uk} numberOfMonths={2} /></PopoverContent></Popover>;
}
function Brand() { return <Link to="/" className="flex items-center gap-2 px-2 font-semibold"><span className="grid size-7 place-items-center rounded-md bg-foreground text-background"><Megaphone className="size-4" /></span><span className="group-data-[collapsible=icon]:hidden">Кривда</span></Link>; }
function Menu({ to, title, icon }: { to: string; title: string; icon: ReactNode }) { return <SidebarMenuItem><SidebarMenuButton render={<NavLink end={to === "/"} to={to} />} tooltip={title}>{icon}<span>{title}</span></SidebarMenuButton></SidebarMenuItem>; }
export function Shell() { return <SidebarProvider><Sidebar collapsible="icon"><SidebarHeader><Brand /></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Аналітика</SidebarGroupLabel><SidebarMenu><Menu to="/" title="Огляд" icon={<LayoutDashboard />} /><Menu to="/entities" title="Сутності" icon={<Shapes />} /><Menu to="/channels" title="Канали" icon={<Radio />} /></SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><SidebarMenu><SidebarMenuItem><SidebarMenuButton disabled><CircleAlert /><span>Трекер атак</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter></Sidebar><SidebarInset><header className="sticky top-0 z-10 flex h-14 items-center border-b bg-background/90 px-4"><SidebarTrigger /></header><Outlet /></SidebarInset></SidebarProvider>; }
function Page({ title, subtitle, children, range = true }: { title: string; subtitle: string; children: ReactNode; range?: boolean }) { return <main className="mx-auto max-w-7xl space-y-5 p-4 md:p-6"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>{range && <DateRange />}</div>{children}</main>; }
function Load() { return <div className="grid gap-3 md:grid-cols-3">{[1,2,3].map(x => <Skeleton key={x} className="h-24" />)}</div>; }
function Metric({ title, value }: { title: string; value: number }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-semibold">{number(value)}</p></CardContent></Card>; }
function Chart({ data }: { data: Daily[] }) { return <ChartContainer className="h-60 w-full" config={{ claim_count: { label: "Твердження", color: "var(--chart-1)" }, post_count: { label: "Дописи", color: "var(--chart-2)" } }}><AreaChart data={data}><CartesianGrid vertical={false} /><XAxis dataKey="date" tickFormatter={labelDate} /><ChartTooltip content={<ChartTooltipContent />} /><Area dataKey="claim_count" stroke="var(--color-claim_count)" fill="var(--color-claim_count)" fillOpacity={.15} /><Area dataKey="post_count" stroke="var(--color-post_count)" fill="transparent" /></AreaChart></ChartContainer>; }
function Pager({ page, param = "offset" }: { page: Page<unknown>; param?: string }) { const [p, setP] = useSearchParams(); const end = Math.min(page.offset + page.items.length, page.total); const change = (offset: number) => { p.set(param, String(Math.max(0, offset))); setP(p); }; return <div className="mt-4 flex items-center justify-between text-sm text-muted-foreground"><span>{page.total ? "Показано " + (page.offset + 1) + "–" + end + " із " + page.total : "Немає результатів"}</span><div className="flex items-center gap-2"><Button size="icon-sm" variant="outline" disabled={!page.offset} onClick={() => change(page.offset - size)}><ChevronLeft /></Button><span>{Math.floor(page.offset / size) + 1}</span><Button size="icon-sm" variant="outline" disabled={end >= page.total} onClick={() => change(page.offset + size)}><ChevronRight /></Button></div></div>; }

export function DashboardPage() { const [p] = useSearchParams(); const d = dates(p); const query = useQuery({ queryKey: ["dashboard", d], queryFn: () => apiClient.dashboard(d) }); if (!query.data) return <Page title="Огляд" subtitle="Оперативна картина"><Load /></Page>; const data = query.data; return <Page title="Огляд" subtitle="Стан збору та аналізу"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Дописи" value={data.summary.post_count} /><Metric title="Твердження" value={data.summary.claim_count} /><Metric title="Сутності" value={data.summary.entity_count} /><Metric title="Канали" value={data.summary.channel_count} /></section><Card><CardHeader><CardTitle>Динаміка аналізу</CardTitle></CardHeader><CardContent><Chart data={data.daily} /></CardContent></Card><Claims dates={d} /></Page>; }
export function EntitiesPage() { const [p, setP] = useSearchParams(); const d = dates(p); const filters = { q: p.get("q") ?? "", coarse_type: p.get("type") ?? undefined, monitored: p.get("monitored") ?? undefined, sort: p.get("sort") ?? "name", offset: Number(p.get("offset") ?? 0) }; const query = useQuery({ queryKey: ["entities", d, filters], queryFn: () => apiClient.entities(d, filters) }); const set = (key: string, val: string) => { if (val === "all") p.delete(key); else p.set(key, val); p.delete("offset"); setP(p); }; return <Page title="Сутності" subtitle="Реєстр і результати аналізу"><Card><CardContent className="space-y-4 p-4"><div className="grid gap-2 md:grid-cols-4"><Input value={filters.q} placeholder="Пошук сутності" onChange={e => set("q", e.target.value)} /><Select value={filters.coarse_type ?? "all"} onValueChange={v => set("type", v)}><SelectTrigger><SelectValue placeholder="Тип" /></SelectTrigger><SelectContent><SelectItem value="all">Усі типи</SelectItem>{Object.entries(types).map(([k,v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><Select value={filters.monitored ?? "all"} onValueChange={v => set("monitored", v)}><SelectTrigger><SelectValue placeholder="Статус" /></SelectTrigger><SelectContent><SelectItem value="all">Усі статуси</SelectItem><SelectItem value="true">Відстежуються</SelectItem><SelectItem value="false">Не відстежуються</SelectItem></SelectContent></Select><Select value={filters.sort} onValueChange={v => set("sort", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="name">За назвою</SelectItem><SelectItem value="mentions">За згадуваннями</SelectItem><SelectItem value="positive">За позитивними</SelectItem><SelectItem value="negative">За негативними</SelectItem></SelectContent></Select></div>{!query.data ? <Load /> : <><EntityRows items={query.data.items} /><Pager page={query.data} /></>}</CardContent></Card></Page>; }
function EntityRows({ items }: { items: Entity[] }) { return <Table><TableHeader><TableRow><TableHead>Сутність</TableHead><TableHead>Згадування</TableHead><TableHead>Позитивні</TableHead><TableHead>Негативні</TableHead></TableRow></TableHeader><TableBody>{items.map(x => <TableRow key={x.id}><TableCell><Link className="font-medium hover:underline" to={"/entities/" + x.id}>{x.canonical_name}</Link></TableCell><TableCell>{number(x.mention_count)}</TableCell><TableCell className="text-emerald-700">{number(x.positive_count)}</TableCell><TableCell className="text-rose-700">{number(x.negative_count)}</TableCell></TableRow>)}</TableBody></Table>; }
export function EntityPage() { const { id = "" } = useParams(); const [p, setP] = useSearchParams(); const d = dates(p); const channelOffset = Number(p.get("channel_offset") ?? 0); const evidenceOffset = Number(p.get("evidence_offset") ?? 0); const channel = p.get("channel") ?? undefined; const stance = p.get("stance") as Stance | undefined; const rhetoric = p.get("rhetoric") as RhetoricLabel | undefined; const profile = useQuery({ queryKey: ["entity", id, d, channelOffset, channel], queryFn: () => apiClient.entity(id, d, channelOffset, channel) }); const evidence = useQuery({ queryKey: ["evidence", id, d, channel, stance, rhetoric, evidenceOffset], queryFn: () => apiClient.evidence(id, d, channel, stance, rhetoric, evidenceOffset), enabled: !!profile.data?.entity.monitored }); const set = (key: string, val: string) => { if (val === "all") p.delete(key); else p.set(key, val); p.delete("evidence_offset"); setP(p); }; if (!profile.data) return <Page title="Сутність" subtitle="Завантаження"><Load /></Page>; const data = profile.data; return <Page title={data.entity.canonical_name} subtitle={types[data.entity.coarse_type] ?? data.entity.coarse_type}>{!data.entity.monitored ? <Card><CardContent className="p-8 text-muted-foreground">Сутність не відстежується.</CardContent></Card> : <><section className="grid gap-3 sm:grid-cols-3"><Metric title="Згадування" value={data.summary.mention_count} /><Metric title="Позитивні" value={data.summary.positive_count} /><Metric title="Негативні" value={data.summary.negative_count} /></section><Card><CardHeader><CardTitle>Типи атак</CardTitle></CardHeader><CardContent><div className="mb-4 max-w-sm"><Select value={channel ?? "all"} onValueChange={v => set("channel", v)}><SelectTrigger><SelectValue placeholder="Канал" /></SelectTrigger><SelectContent><SelectItem value="all">Усі канали</SelectItem>{data.channel_options.map(x => <SelectItem key={x.id} value={String(x.id)}>{x.title}</SelectItem>)}</SelectContent></Select></div><AttackChart data={data.rhetoric} selected={rhetoric} onSelect={key => set("rhetoric", key ?? "all")} /></CardContent></Card><Card><CardHeader><CardTitle>Канали</CardTitle></CardHeader><CardContent><ChannelRows items={data.channels.items} entity /><Pager page={data.channels} param="channel_offset" /></CardContent></Card><Card><CardHeader><CardTitle>Докази</CardTitle></CardHeader><CardContent><div className="mb-3 flex gap-2"><Select value={stance ?? "all"} onValueChange={v => set("stance", v)}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Позитивні й негативні</SelectItem><SelectItem value="позитивне">Позитивні</SelectItem><SelectItem value="негативне">Негативні</SelectItem></SelectContent></Select></div>{!evidence.data ? <Load /> : <><EvidenceRows items={evidence.data.items} /><Pager page={evidence.data} param="evidence_offset" /></>}</CardContent></Card></>}</Page>; }
function AttackChart({ data, selected, onSelect }: { data: RhetoricAggregate[]; selected?: RhetoricLabel; onSelect: (key?: RhetoricLabel) => void }) { const chartData = data.map(item => ({ ...item, label: rhetoricLabels[item.key], detail: number(item.count) + " · " + (item.share * 100).toLocaleString("uk-UA", { maximumFractionDigits: 1 }) + "%" })); return <div className="space-y-3"><div className="flex items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Частка від усіх розмічених атак</p><Button size="sm" variant="ghost" disabled={!selected} onClick={() => onSelect()}>Усі типи</Button></div><ChartContainer className="h-72 w-full" config={{ count: { label: "Кількість", color: "var(--chart-1)" } }}><BarChart data={chartData} layout="vertical" margin={{ left: 12, right: 64 }}><CartesianGrid horizontal={false} /><YAxis type="category" dataKey="label" width={220} tickLine={false} axisLine={false} /><XAxis type="number" allowDecimals={false} hide /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="count" radius={4}>{chartData.map(item => <Cell key={item.key} fill={item.key === selected ? "var(--chart-2)" : "var(--chart-1)"} className="cursor-pointer" onClick={() => onSelect(item.key === selected ? undefined : item.key)} />)}<LabelList dataKey="detail" position="right" className="fill-foreground text-xs" /></Bar></BarChart></ChartContainer></div>; }
function ChannelRows({ items, entity = false }: { items: Summary[]; entity?: boolean }) { return <Table><TableHeader><TableRow><TableHead>Канал</TableHead><TableHead>{entity ? "Згадування" : "Дописи"}</TableHead><TableHead>Позитивні</TableHead><TableHead>Негативні</TableHead></TableRow></TableHeader><TableBody>{items.map(x => <TableRow key={x.id}><TableCell>{x.title}</TableCell><TableCell>{number(entity ? x.claim_count : x.post_count)}</TableCell><TableCell className="text-emerald-700">{number(x.positive_count)}</TableCell><TableCell className="text-rose-700">{number(x.negative_count)}</TableCell></TableRow>)}</TableBody></Table>; }
export function ChannelsPage() { const [p] = useSearchParams(); const d = dates(p); const offset = Number(p.get("offset") ?? 0); const query = useQuery({ queryKey: ["channels", d, offset], queryFn: () => apiClient.channels(d, offset) }); if (!query.data) return <Page title="Канали" subtitle="Порівняння активності"><Load /></Page>; return <Page title="Канали" subtitle="Джерела та результати аналізу"><Card><CardHeader><CardTitle>Активність</CardTitle></CardHeader><CardContent><Chart data={query.data.daily} /></CardContent></Card><Card><CardContent className="p-4"><ChannelRows items={query.data.items} /><Pager page={query.data} /></CardContent></Card></Page>; }
function ClaimEntityFilter({ selected, onSelect }: { selected?: string; onSelect: (entity?: Entity) => void }) { const [text, setText] = useState(""); const results = useQuery({ queryKey: ["claim-entity-search", text], queryFn: () => apiClient.entities({}, { q: text }), enabled: text.trim().length >= 2 }); const showChoices = Boolean(selected || results.data?.items.length); return <div className="relative min-w-52"><Input value={text} placeholder={selected ? "Сутність вибрано" : "Знайти сутність"} onChange={e => setText(e.target.value)} />{showChoices && <div className="absolute z-20 mt-1 w-full overflow-hidden rounded-md border bg-popover shadow-sm">{selected && <button className="block w-full px-3 py-2 text-left text-sm hover:bg-accent" onClick={() => { setText(""); onSelect(); }}>Прибрати фільтр сутності</button>}{results.data?.items.map(entity => <button key={entity.id} className="block w-full px-3 py-2 text-left text-sm hover:bg-accent" onClick={() => { setText(entity.canonical_name); onSelect(entity); }}>{entity.canonical_name}</button>)}</div>}</div>; }
function Claims({ dates: d }: { dates: DateRange }) { const [p, setP] = useSearchParams(); const filters = { search: p.get("claim_q") ?? "", entity_id: p.get("claim_entity") ?? undefined, stance: p.get("claim_stance") as Stance | undefined, offset: Number(p.get("claim_offset") ?? 0) }; const query = useQuery({ queryKey: ["claims", d, filters], queryFn: () => apiClient.claims(d, filters) }); const set = (key: string, val: string) => { if (val === "all") p.delete(key); else p.set(key, val); p.delete("claim_offset"); setP(p); }; const selectEntity = (entity?: Entity) => { if (entity) p.set("claim_entity", String(entity.id)); else p.delete("claim_entity"); p.delete("claim_offset"); setP(p); }; return <Card><CardHeader><CardTitle className="flex gap-2"><FileSearch className="size-4" />Твердження</CardTitle></CardHeader><CardContent><div className="mb-3 flex flex-wrap gap-2"><Input className="max-w-sm" value={filters.search} placeholder="Пошук тверджень" onChange={e => set("claim_q", e.target.value)} /><ClaimEntityFilter selected={filters.entity_id} onSelect={selectEntity} /><Select value={filters.stance ?? "all"} onValueChange={v => set("claim_stance", v)}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Усі оцінки</SelectItem><SelectItem value="позитивне">Позитивні</SelectItem><SelectItem value="негативне">Негативні</SelectItem><SelectItem value="відсутнє">Без оцінки</SelectItem></SelectContent></Select></div>{!query.data ? <Load /> : <><Table><TableHeader><TableRow><TableHead>Твердження</TableHead><TableHead>Сутність</TableHead><TableHead>Канал</TableHead></TableRow></TableHeader><TableBody>{query.data.items.map(x => <TableRow key={x.claim_id}><TableCell><Link to={"/posts/" + x.post_id}>{x.normalized_text}</Link></TableCell><TableCell>{x.entity_name}</TableCell><TableCell>{x.channel_title}</TableCell></TableRow>)}</TableBody></Table><Pager page={query.data} param="claim_offset" /></>}</CardContent></Card>; }
function EvidenceRows({ items }: { items: Evidence[] }) { return <div className="divide-y">{items.map(x => <Link to={"/posts/" + x.post_id} key={x.claim_id} className="block py-3"><div className="flex justify-between"><span>{x.channel_title}</span><Badge className={colors[x.stance]} variant="secondary">{x.stance}</Badge></div><p className="mt-1 text-sm">{x.normalized_text}</p></Link>)}</div>; }
export function PostPage() { const { id = "" } = useParams(); const query = useQuery({ queryKey: ["post", id], queryFn: () => apiClient.post(id) }); if (!query.data) return <Page title="Допис" subtitle="Завантаження" range={false}><Load /></Page>; return <Page title={query.data.channel_title} subtitle={new Date(query.data.published_at).toLocaleString("uk-UA")} range={false}><Card><CardContent className="whitespace-pre-wrap p-6">{query.data.content}</CardContent></Card></Page>; }
